import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  /*
     `.claude` holds agent scratch space, including worktree copies of this project. Linting those
     reported 236 errors in files that are not part of the study and cannot be edited here, which
     buried the handful that are real.
  */
  globalIgnores(['dist', '.claude']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    rules: {
      // Honour the `_`-prefix convention for intentionally-unused params/vars
      // (e.g. reserved callback args, signatures kept for clarity).
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
    },
  },
  {
    // Generated by the Chakra UI CLI (`npx @chakra-ui/cli snippet add`), so they are regenerated
    // rather than hand-edited. Their shape trips two rules: they re-export Chakra parts as
    // `export const X = Chakra.Part` and put hooks such as useColorMode beside components, which
    // react-refresh cannot recognize as components (affects dev hot reload only); and they declare
    // `interface XProps extends Y {}` (no-empty-object-type; type-only). Every other rule still
    // applies here.
    files: ['src/components/ui/**/*.{ts,tsx}'],
    rules: {
      'react-refresh/only-export-components': 'off',
      '@typescript-eslint/no-empty-object-type': 'off',
    },
  },
])
